import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles(() => ({
  darkBackgroundForModalWindow: {
    position: "fixed",
    width: "100%",
    height: "100%",
    left: "0",
    top: "0",
    backgroundColor: "rgba(0, 0, 0, 0.69)",
    zIndex: "1000",
    "@media (min-width:700px)": {
      height: "495%",
    },
    "@media (min-width:768px)": {
      height: "470%",
    },
    "@media (min-width:1200px)": {
      height: "480%",
    },
  },
  modalWindowRegister: {
    position: "absolute",
    width: "253px",
    height: "1025px",
    left: "50%",
    transform: "translateX(-50%)",
    background: "#F9F9F9",
    zIndex: "1000",
    paddingLeft: "2px",
    borderRadius: "2px",
    "@media (min-width:320px)": {
      width: "270px",
      height: "1100px",
      margin: "40px auto",
    },
    "@media (min-width:700px)": {
      width: "550px",
      height: "455px",
      margin: "40px auto",
    },
    "@media (min-width:1200px)": {
      width: "905px",
      height: "711px",
      marginTop: "40px",
    },
  },
  headerInTheModalWindow: {
    backgroundColor: "#F9F9F9",
    height: "35px",
    "@media (min-width:480px)": {
      height: "53px",
    },
    "@media (min-width:700px)": {
      height: "77px",
    },
    "@media (min-width:1200px)": {
      height: "133px",
    },
  },
  headerRegister: {
    position: "absolute",
    width: "235px",
    height: "29px",
    fontSize: "14px",
    left: "24px",
    top: "14px",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "bold",
    lineHeight: "29px",

    color: "#212052",
    "@media (min-width:480px)": {
      fontSize: "10px",
      left: "24px",
      top: "10px",
    },
    "@media (min-width:700px)": {
      fontSize: "14px",
      left: "35px",
      top: "19px",
    },
    "@media (min-width:1200px)": {
      fontSize: "24px",
      left: "59px",
      top: "32px",
    },
  },
  textInHeaderRegister: {
    position: "absolute",
    width: "80%",
    height: "32px",
    fontSize: "12px",
    left: "24px",
    top: "42px",
    lineHeight: "19px",

    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWight: "500",

    color: "#474747",
    "@media (min-width:480px)": {
      fontSize: "10px",
      left: "24px",
      top: "37px",
      lineHeight: "7px",
    },
    "@media (min-width:700px)": {
      fontSize: "12px",
      left: "35px",
      top: "42px",
      lineHeight: "19px",
    },
    "@media (min-width:1200px)": {
      fontSize: "16px",
      left: "59px",
      top: "66px",
      lineHeight: "32px",
    },
  },
  cropmanInHeader: {
    fontWeight: "bolder",
  },
  plansWindows: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    marginLeft: "0px",
    marginRight: "38px",
    position: "relative",
    marginTop: "35px",
    "@media (min-width:320px)": {
      display: "flex",
      marginLeft: "0px",
      marginRight: "38px",
      flexDirection: "column",
      marginTop: "40px",
    },
    "@media (min-width:700px)": {
      display: "flex",
      flexDirection: "row",
      marginLeft: "6px",
      marginRight: "10px",
      marginTop: "0px",
    },
    "@media (min-width:1200px)": {
      display: "flex",
      flexDirection: "row",
      marginLeft: "70px",
      marginRight: "98px",
      marginTop: "0px",
    },
  },
  planGender: {
    width: "140px",
    height: "294px",
    backgroundColor: "#FFFFFF",
    marginTop: "15px",
    marginLeft: "30px",
    "@media (min-width:320px)": {
      width: "224px",
      height: "320px",
      marginLeft: "20px",
    },
    "@media (min-width:700px)": {
      width: "260px",
      height: "320px",
    },
    "@media (min-width:1200px)": {
      width: "235px",
      height: "499px",
    },
  },
  titleInWindow: {
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "20px",
    textAlign: "center",
    color: "#5E61A8",
    "@media (min-width:320px)": {
      margin: "15 auto",
      fontSize: "14px",
      paddingTop: 15,
    },
    "@media (min-width:700px)": {
      margin: "15 auto",
      fontSize: "14px",
    },
    "@media (min-width:1200px)": {
      margin: "16px auto",
      fontSize: "16px",
    },
  },
  titleInWindowPlus: {
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "20px",
    textAlign: "center",
    color: "#EA4165",
    "@media (min-width:320px)": {
      margin: "15 auto",
      fontSize: "14px",
      paddingTop: 15,
    },
    "@media (min-width:700px)": {
      margin: "15 auto",

      fontSize: "14px",
    },
    "@media (min-width:1200px)": {
      margin: "16px auto",
      fontSize: "16px",
    },
  },
  standartTextInWindowFirstLine: {
    width: "169px",
    height: "25px",
    marginLeft: "5px",
    marginTop: "10px",
    fontSize: "12px",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "normal",
    color: "#000000",
    "@media (min-width:320px)": {
      width: "170px",
      height: "20px",
      marginLeft: "14px",
      marginTop: "18px",
      fontSize: "12px",
      lineHeight: "14px",
    },
    "@media (min-width:680px)": {
      width: "139px",
      height: "25px",
      marginLeft: "13px",
      marginTop: "15px",
      fontSize: "12px",
      lineHeight: "17px",
    },
    "@media (min-width:1200px)": {
      width: "200px",
      height: "34px",
      marginLeft: "25px",
      marginTop: "25px",
      fontSize: "14px",
      lineHeight: "17px",
    },
  },
  standartTextInWindow: {
    width: "139px",
    height: "25px",
    marginLeft: "5px",
    marginTop: "25px",
    fontSize: "12px",
    lineHeight: "17px",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "normal",
    color: "#000000",

    "@media (min-width:320px)": {
      width: "170px",
      height: "20px",
      marginLeft: "14px",
      marginTop: "18px",
      fontSize: "12px",
      lineHeight: "14px",
    },
    "@media (min-width:700px)": {
      width: "139px",
      height: "25px",
      marginLeft: "13px",
      marginTop: "25px",
      fontSize: "12px",
      lineHeight: "17px",
    },
    "@media (min-width:1200px)": {
      width: "200px",
      height: "34px",
      marginLeft: "25px",
      marginTop: "45px",
      fontSize: "14px",
      lineHeight: "17px",
    },
  },
  bolderText: {
    fontWeight: "bolder",
  },
  smallTextInWindow: {
    width: "125px",
    height: "25px",
    marginLeft: "15px",
    marginTop: "9px",
    fontSize: "7px",
    lineHeight: "151.4%",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "300",
    color: "#575757",
    "@media (min-width:320px)": {
      width: "180px",
      height: "25px",
      marginLeft: "15px",
      marginTop: "9px",
      fontSize: "9px",
      lineHeight: "151.4%",
    },
    "@media (min-width:700px)": {
      width: "125px",
      height: "25px",
      marginLeft: "15px",
      marginTop: "14px",
      fontSize: "7px",
      lineHeight: "151.4%",
    },
    "@media (min-width:1200px)": {
      width: "190px",
      height: "56px",
      marginLeft: "22px",
      marginTop: "9px",
      fontSize: "10px",
      lineHeight: "151.4%",
    },
  },
  planPriceBasic: {
    position: "relative",
    width: "47px",
    height: "24px",
    marginTop: "32px",
    marginLeft: "50px",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "20px",
    lineHeight: "124px",
    color: "#EA4165",
    "@media (min-width:320px)": {
      margin: "0 auto",
      paddingTop: 60,
      fontSize: "16px",
    },
    "@media (min-width:700px)": {
      position: "absolute",
      width: "47px",
      height: "24px",
      bottom: "133px",
      marginLeft: "57px",
      fontSize: "15px",
      lineHeight: "124px",
    },
    "@media (min-width:1200px)": {
      position: "absolute",
      width: "47px",
      height: "24px",
      bottom: "170px",
      marginLeft: "94px",
      fontSize: "20px",
      lineHeight: "124px",
    },
  },
  planPricePro: {
    position: "relative",
    width: "47px",
    height: "24px",
    marginTop: "-20px",
    marginLeft: "50px",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "20px",
    lineHeight: "124px",
    color: "#EA4165",
    "@media (min-width:320px)": {
      margin: "0 auto",
      paddingBottom: 10,
      fontSize: "16px",
    },
    "@media (min-width:700px)": {
      position: "absolute",

      bottom: "110px",
      marginLeft: "59px",
      fontSize: "15px",
    },
    "@media (min-width:1200px)": {
      position: "absolute",
      width: "47px",
      height: "24px",
      bottom: "150px",
      marginLeft: "94px",
      fontSize: "20px",
    },
  },
  planPricePlus: {
    position: "relative",
    bottom: "30px",
    fontFamily: "Montserrat, sans-serif",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "26px",
    color: "#EA4165",
    "@media (min-width:320px)": {
      paddingTop: 70,
      fontSize: "20px",
      paddingLeft: 80,
    },
    "@media (min-width:700px)": {
      bottom: "47px",
      right: 28,
      fontSize: "15px",
    },
    "@media (min-width:1200px)": {
      bottom: "37px",
      fontSize: "26px",
      marginLeft: 4,
    },
  },
  smallDollarSign: {
    fontSize: "10px",
    "@media (min-width:320px)": {
      fontSize: "8px",
    },
    "@media (min-width:700px)": {
      fontSize: "7px",
      marginLeft: "10px",
    },
    "@media (min-width:1200px)": {
      fontSize: "10px",
    },
  },
  notBoldMonth: {
    fontWeight: "normal",
    fontSize: "10px",
    "@media (min-width:320px)": {
      fontSize: "8px",
    },
    "@media (min-width:700px)": {
      fontSize: "7px",
    },
    "@media (min-width:1200px)": {
      fontSize: "10px",
    },
  },
  buttonRedServiceBasic: {
    bottom: "35px",
    margin: "0 auto",
    "@media (min-width:320px)": {
      position: "absolute",
      top: "250px",
      left: 51,
    },
    "@media (min-width:700px)": {
      position: "absolute",
      top: "250px",
      left: 24,
    },
    "@media (min-width:1200px)": {
      top: "424px",
      position: "absolute",

      left: 16,
    },
  },
  buttonRedServicePro: {
    position: "relative",
    "@media (min-width:320px)": {
      position: "absolute",
      top: 593,
      left: 51,
    },
    "@media (min-width:700px)": {
      position: "absolute",
      left: 200,
      top: 250,
    },
    "@media (min-width:1200px)": {
      top: "424px",
      position: "absolute",

      left: 261,
    },
  },
  buttonRedServicePlus: {
    position: "relative",
    "@media (min-width:320px)": {
      position: "absolute",
      top: 930,
      left: 51,
    },
    "@media (min-width:700px)": {
      position: "absolute",
      left: 370,
      top: 250,
    },
    "@media (min-width:1200px)": {
      top: "424px",
      position: "absolute",

      left: 505,
    },
  },
  cross: {
    width: "11px",
    height: "11px",
    float: "right",
    marginTop: "11px",
    marginRight: "11px",
    cursor: "pointer",
    "@media (min-width:480px)": {
      width: "10px",
      height: "10px",
      float: "right",
      marginTop: "10px",
      marginRight: "10px",
    },
    "@media (min-width:700px)": {
      width: "12px",
      height: "12px",
      float: "right",
      marginTop: "12px",
      marginRight: "12px",
    },
    "@media (min-width:1200px)": {
      width: "13px",
      height: "13px",
      float: "right",
      marginTop: "30px",
      marginRight: "28px",
    },
  },
  coffeeCup: {
    width: "40px",
    height: "50px",
    float: "right",
    marginTop: "60px",
    "@media (min-width:480px)": {
      width: "40px",
      height: "50px",
      float: "right",
      marginTop: "30px",
      marginRight: "55px",
    },
    "@media (min-width:700px)": {
      width: "64px",
      height: "80px",
      float: "right",
      marginTop: "15px",
      marginRight: "40px",
    },
    "@media (min-width:1200px)": {
      width: "80px",
      height: "100px",
      float: "right",
      marginTop: "52px",
      marginRight: "136px",
    },
  },
  starsNearCross: {
    position: "absolute",
    width: "8px",
    height: "12.8px",
    left: "244px",
    top: "0",
    "@media (min-width:480px)": {
      width: "12px",
      height: "19px",
      left: "366px",
      top: "0",
    },
    "@media (min-width:700px)": {
      width: "17.5px",
      height: "28px",
      left: "508px",
      top: "0",
    },
    "@media (min-width:1200px)": {
      width: "29px",
      height: "47px",
      left: "819px",
      top: "0",
    },
  },
  starsFromRightSide: {
    position: "absolute",
    width: "17.5px",
    height: "28px",
    left: "220px",
    top: "330px",
    "@media (min-width:480px)": {
      width: "12px",
      height: "19px",
      left: "360px",
      top: "160px",
    },
    "@media (min-width:700px)": {
      width: "17.5px",
      height: "28px",
      left: "510px",
      top: "230px",
    },
    "@media (min-width:1200px)": {
      width: "29px",
      height: "47px",
      left: "842px",
      top: "336px",
    },
  },
  starsFromBottom: {
    position: "absolute",
    width: "17.5px",
    height: "28px",
    left: "74px",
    top: "1000px",
    transform: "rotate(90deg)",
    "@media (min-width:480px)": {
      width: "12px",
      height: "19px",
      left: "30px",
      top: "268px",
    },
    "@media (min-width:700px)": {
      width: "17.5px",
      height: "28px",
      left: "57px",
      top: "392px",
    },
    "@media (min-width:1200px)": {
      width: "29px",
      height: "47px",
      left: "120px",
      top: "673px",
    },
  },
  navlink:{
    textDecoration:'none',
  }
}));

export default useStyles;
